const EXTEND_LOGIC_INTERFACE = "0xa501cf1f";
const PERMISSIONING_LOGIC_INTERFACE = "0xe0f6c5f3";
const RETRACT_LOGIC_INTERFACE = "0xf9fb51c8";
const REPLACE_LOGIC_INTERFACE = "0x631de4d6";
const REGISTER_LOGIC_INTERFACE = "0x32434a2e";
const DEPLOY_LOGIC_INTERFACE = "0x0570b1fa";
const TOKEN_LOGIC_INTERFACE = "0x40c10f19";
const STORAGE_GETTER_LOGIC_INTERFACE = "0xa75cdf14";

export {
    EXTEND_LOGIC_INTERFACE,
    PERMISSIONING_LOGIC_INTERFACE,
    RETRACT_LOGIC_INTERFACE,
    REPLACE_LOGIC_INTERFACE,
    REGISTER_LOGIC_INTERFACE,
    DEPLOY_LOGIC_INTERFACE,
    TOKEN_LOGIC_INTERFACE,
    STORAGE_GETTER_LOGIC_INTERFACE
}